### ISSUE TITLE
Demo should probably test for BBC Master

### ISSUE THREAD

**Issue by kieranhj** [bitshifters/just-rasters#26]
Same as POP and barf if not.

Also might be worth seeing if the demo can boot at PAGE &1900 since lots of people seem to have crappy hacked DFS installed for their MMC devices.

Also add *FX200,3 for safety.

**Comment by kieranhj** [comment]
Done.  Added BASIC program to test Master and ask emu or real hardware.

**Comment by simondotm** [comment]
Only trouble with asking for inputs, is that running the demo on a mobile browser wont work. Unless there's a way to bring up a keyboard I dont know about...

**Comment by kieranhj** [comment]
Good point, that is annoying and I do show it to people on my phone. How about it defaults to emulator and continues after 10 seconds?

**Comment by kieranhj** [comment]
Done.
